---
title: Bellas Blogs and Recipes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    excerpt_separator: "<!--more-->"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header_feature_image: 
    caption: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    header_feature_image: 
    caption: 
- scope:
    path: ''
    type: recipe
  values:
    layout: recipe
<<<<<<< HEAD
    order:

# SITE CONFIGURATION
baseurl: ''  #leave this alone
url: "https://bellapickering.github.io"   #change this to yours
title: Bella Pickering # site's title
description: "A website with blog posts and recipes" # used by search engines

# SITE-SPECIFIC CONFIGURATION
# Change these 2 images for your own site

=======
    order: 
baseurl: ''
url: https://bellapickering.github.io
description: A website with blog posts and recipes
>>>>>>> 8ed764a2077066a2b1c32c2a90ae46f83f79d954
avatar: assets/img/face.jpg
favicon: assets/favicon.ico
gridlayout: false
recipemenu: false
header_text: My blog and my recipes
recipecollection: Your recipe collection
<<<<<<< HEAD

# find an image for your own home page and put it into the images folder
header_feature_image: /uploads/Waves.jpg
recipe_bookcover: /uploads/bookcover.jpg

twitter_username:   #change to your own twitter account
lang: en_gb
# change the following to your name or site name
footer_text:
    "Copyright 2020 My name"
  # Icons
  # If you have any of these accounts add them in here
rss: false  # Make sure you created a feed.xml with feed.xml layout
email_address: # Full email address, e.g. "sam@example.com"
facebook:
flickr:
google_plus:
instagram:bella_pickering12
linkedin:  # Full URL
pinterest:
soundcloud:
twitter: # "twitter username"
youtube:

# Sharing options
=======
header_feature_image: "/uploads/pages.jpg"
recipe_bookcover: "/uploads/bookcover.jpg"
twitter_username: 
lang: en_gb
footer_text: Copyright 2020 My name
rss: false
email_address: 
facebook: 
flickr: 
google_plus: 
instagram: 
linkedin: 
pinterest: 
soundcloud: 
twitter: 
youtube: 
>>>>>>> 8ed764a2077066a2b1c32c2a90ae46f83f79d954
share_buttons:
  facebook: true
  twitter: true
  tumblr: 
  pinterest: 
  linkedin: 
  email: true
google_analytics: 
disqus_shortname: 
str_follow_on: Follow on
str_rss_follow: Follow RSS feed
str_share_on: Share on
str_add_to: Add to
str_email: Email
str_tweet: Tweet
str_pin_it: Pin it
str_next_post: Next post
str_previous_post: Previous post
str_next_page: Next
str_previous_page: Prev
str_javascript_required_disqus: Please enable JavaScript to view comments.
post_navigation: true
paginate: 10
paginate_path: blog/page:num
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- ".jekyll-cache"
- Gemfile
- README.md
