---
title: Bella Pickering
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    excerpt_separator: "<!--more-->"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header_feature_image:
    caption:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    header_feature_image:
    caption:
- scope:
    path: ''
    type: recipe
  values:
    layout: recipe
    order:
baseurl: ''
url: https://bellapickering.github.io
description: A website with blog posts and recipes
avatar: assets/img/avatar.jpg
favicon: assets/favicon.ico
gridlayout: false
recipemenu: false
header_text: This is Africa
recipecollection: The Big Catch, Hooked and Cooked.

# find an image for your own home page and put it into the images folder
header_feature_image: /uploads/eliphants.jpeg
recipe_bookcover: /uploads/TheBigCatch.jpg

twitter_username:   #change to your own twitter account
lang: en_gb
# change the following to your name or site name
footer_text:
    "Copyright 2020 Bella Pickering"
  # Icons
  # If you have any of these accounts add them in here
rss: false  # Make sure you created a feed.xml with feed.xml layout
email_address: 16103785@brookes.ac.uk # Full email address, e.g. "sam@example.com"
facebook:
flickr:
google_plus:
instagram: bella_pickering12
linkedin:  # Full URL
pinterest:
soundcloud:
twitter: # "twitter username"
youtube:

# Sharing options
share_buttons:
  facebook: true
  twitter: true
  tumblr:
  pinterest:
  linkedin:
  email: true
google_analytics:
disqus_shortname:
str_follow_on: Follow on
str_rss_follow: Follow RSS feed
str_share_on: Share on
str_add_to: Add to
str_email: Email
str_tweet: Tweet
str_pin_it: Pin it
str_next_post: Next post
str_previous_post: Previous post
str_next_page: Next
str_previous_page: Prev
str_javascript_required_disqus: Please enable JavaScript to view comments.
post_navigation: true
paginate: 10
paginate_path: blog/page:num
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- ".jekyll-cache"
- Gemfile
- README.md
